#!/usr/bin/env python3
import genanki
import os

def create_model():
    """Create the Anki card model with Front/Back fields."""
    return genanki.Model(
        1847293847,  # Unique random 10-digit number
        'Founder Terms Q&A',
        fields=[
            {'name': 'Front'},
            {'name': 'Back'},
        ],
        templates=[
            {
                'name': 'Card 1',
                'qfmt': '{{Front}}',
                'afmt': '{{FrontSide}}<hr id="answer">{{Back}}',
            },
        ],
        css='''
            .card {
                font-family: arial;
                font-size: 20px;
                text-align: left;
                color: black;
                background-color: white;
                padding: 20px;
            }
            .back {
                text-align: left;
                white-space: pre-wrap;
            }
        '''
    )

def create_deck():
    """Create the Anki deck."""
    return genanki.Deck(
        2847392847,  # Unique random 10-digit number
        'Founder Terms'
    )

def get_terms():
    """Define all the founder terms and their definitions."""
    terms = [
        ("Term Sheet", "A non-binding agreement that outlines the key terms and conditions under which an investor will invest in a company. It serves as the foundation for more detailed legal documents and typically includes valuation, investment amount, ownership percentage, voting rights, board composition, liquidation preferences, and anti-dilution protections. While not legally binding in most aspects, some provisions like exclusivity and confidentiality are binding. Negotiating a term sheet is a critical milestone as it sets the framework for the entire investment relationship."),

        ("Due Diligence", "The comprehensive investigation and analysis process conducted by investors before making an investment decision. This includes reviewing financial statements, legal documents, intellectual property, customer contracts, team backgrounds, technology architecture, market analysis, and potential risks. Due diligence can take weeks to months depending on the stage and typically involves lawyers, accountants, and technical experts. The goal is to verify claims made by founders and uncover any potential issues that could affect the investment decision or valuation."),

        ("Cap Table", "A capitalization table - a spreadsheet or database that tracks all equity ownership in a company, including founders' shares, employee stock options, investor preferred shares, warrants, and convertible securities. It shows who owns what percentage of the company on both a basic and fully diluted basis. Maintaining an accurate cap table is crucial for understanding ownership stakes, modeling future fundraising scenarios, and ensuring compliance during exits. Cap table management becomes increasingly complex with each funding round and should be managed carefully using specialized software."),

        ("Pre-money Valuation", "The valuation of a company immediately before receiving new investment capital. This figure is negotiated between founders and investors and determines how much of the company investors will own for their investment. For example, if a company has a $10M pre-money valuation and raises $2M, the post-money valuation becomes $12M, and investors own approximately 16.7% of the company. Pre-money valuation reflects the company's perceived value based on traction, team, market opportunity, and comparable companies."),

        ("Post-money Valuation", "The valuation of a company immediately after receiving new investment capital, calculated as pre-money valuation plus the amount invested. This represents the total value of the company including the new capital and determines the exact ownership percentage for new investors. Post-money valuation is what appears in headlines about funding rounds and is used to calculate the company's worth on the cap table. Understanding the distinction between pre-money and post-money is essential for calculating dilution accurately."),

        ("Dilution", "The reduction in ownership percentage that occurs when a company issues new shares, typically during fundraising rounds or when stock options are exercised. If you own 10% of a company and it raises money by issuing new shares representing 20% of the company, your ownership drops to 8%. While dilution reduces percentage ownership, it can be positive if the company's value increases substantially. Founders must balance the need for capital with maintaining meaningful ownership stakes. Anti-dilution provisions can protect against certain types of dilution."),

        ("Pro Rata Rights", "The contractual right given to existing investors to invest in future funding rounds to maintain their ownership percentage and avoid dilution. For example, if an investor owns 10% of a company and has pro rata rights, they can invest 10% of the next funding round. These rights are typically reserved for lead investors or those who invest above a certain threshold. Pro rata rights are valuable because they allow successful investors to increase their position in winning companies, though they're not obligated to exercise these rights."),

        ("Lead Investor", "The primary investor in a funding round who typically invests the largest amount, sets the terms through term sheet negotiation, conducts due diligence, and takes a board seat. Lead investors provide validation and confidence for other investors to follow. They often take an active role in supporting the company through board participation, introductions, and strategic guidance. Having a strong lead investor makes it much easier to close a funding round, as other investors often follow the lead's terms with minimal negotiation."),

        ("Syndicate", "A group of investors who pool their capital together to invest in a company, typically organized by a lead investor or syndicate lead. Syndicates allow smaller investors to participate in deals they couldn't access individually and help companies close larger rounds without managing dozens of individual investor relationships. The lead typically negotiates terms and conducts due diligence on behalf of the group. Angel syndicates have become increasingly popular through platforms like AngelList, democratizing access to startup investing while maintaining efficiency for founders."),

        ("SAFE", "Simple Agreement for Future Equity\n\nA financing instrument created by Y Combinator that allows investors to provide capital to a company in exchange for the right to receive equity in a future priced round. Unlike convertible notes, SAFEs have no interest rate or maturity date, making them simpler and more founder-friendly. They convert to equity when a specific trigger event occurs, typically a priced funding round or acquisition. SAFEs include a valuation cap and/or discount rate that determines the conversion price. They've become the standard for early-stage fundraising due to their simplicity and speed of execution."),

        ("Convertible Note", "A debt instrument that starts as a loan but converts into equity during a future financing round, typically at a discount to the price paid by new investors. The note includes an interest rate (usually 2-8%), maturity date (typically 18-24 months), conversion discount (commonly 20%), and often a valuation cap. If the company doesn't raise a qualifying round before maturity, the debt may become due or convert at the cap. Convertible notes allow founders to raise capital quickly without setting a valuation, though they've been largely replaced by SAFEs in many ecosystems."),

        ("Priced Round", "A financing round where the company's valuation is explicitly set and shares are issued at a specific price per share. Unlike SAFEs or convertible notes, priced rounds establish a clear valuation and immediate ownership percentages. They involve issuing a new series of preferred stock (like Series A, B, or C) with specific rights and preferences. Priced rounds require more extensive legal documentation, take longer to close, and cost more in legal fees, but provide clarity on ownership and are necessary as companies mature and raise larger amounts."),

        ("Bridge Financing", "Short-term funding designed to sustain a company until a larger financing round can be closed or another significant milestone is reached. Bridge rounds often use convertible notes or SAFEs to avoid setting a new valuation and can be raised from existing investors or new participants. They're typically smaller than regular rounds and may be necessary when a company needs more time to hit metrics for a strong Series A or when fundraising takes longer than expected. While bridges can provide crucial runway, multiple bridges may signal difficulties in raising a full round."),

        ("Down Round", "A financing round where the company's valuation is lower than the previous round's post-money valuation, resulting in a higher price per share than earlier investors paid. Down rounds are often accompanied by difficult terms like full ratchet anti-dilution, increased liquidation preferences, or management changes. They signal that the company hasn't met growth expectations and can severely dilute founders and employees. Down rounds can create tension between early and new investors and may affect employee morale. However, they can provide necessary capital to turn around struggling companies."),

        ("Runway", "The length of time a company can continue operating at its current burn rate before running out of cash. Calculated by dividing current cash balance by monthly burn rate. For example, with $600K in the bank and $50K monthly burn, the company has 12 months of runway. Founders should typically start fundraising when they have 6-9 months of runway remaining to allow adequate time to close a round. Understanding runway is critical for planning fundraising timelines, making hiring decisions, and managing cash flow to avoid running out of money."),

        ("Burn Rate", "The rate at which a company spends its cash reserves, typically expressed as a monthly figure (monthly burn rate). It's calculated by subtracting revenue from expenses to show the net cash outflow each month. For example, if a company spends $100K monthly on salaries, rent, and other expenses but generates $40K in revenue, the burn rate is $60K/month. Gross burn rate refers to total expenses without considering revenue. Managing burn rate is crucial for extending runway and demonstrating capital efficiency to investors."),

        ("Series A", "The first significant round of institutional venture capital financing after seed funding, typically ranging from $2-15M. Series A investors expect companies to have demonstrated product-market fit, meaningful traction (often $1-3M ARR for SaaS), and a clear path to scale. This round establishes a formal board of directors, introduces preferred stock with liquidation preferences and other investor protections, and sets a clear company valuation. Series A is a major milestone that validates the business model and provides capital to scale sales, marketing, and product development."),

        ("Series B", "The second major institutional funding round, typically raised to scale a proven business model with strong unit economics. Series B rounds usually range from $10-50M and are focused on expanding market share, growing the team significantly, and potentially entering new markets or product lines. Companies raising Series B generally have substantial revenue (often $10M+ ARR), proven customer acquisition channels, and strong retention metrics. Valuation step-ups from Series A should reflect significant progress in revenue, team, and market position."),

        ("Series C", "The third major funding round, typically raised by mature companies looking to scale aggressively, acquire competitors, or expand internationally. Series C rounds often exceed $50M and may involve late-stage VCs, private equity firms, hedge funds, or strategic investors. Companies at this stage usually have substantial revenue (often $50M+ ARR), clear paths to profitability or IPO, and proven business models. Some companies raise Series D, E, or beyond, though excessive fundraising can indicate difficulty reaching profitability or delays in exit opportunities."),

        ("Seed Round", "Early-stage funding typically raised after friends and family or angel investment but before Series A. Seed rounds usually range from $500K to $3M and are used to develop the product, validate product-market fit, and achieve initial traction. Seed investors include angel investors, seed-stage VCs, and accelerators. Companies at seed stage often have a prototype or MVP, early customers, and a founding team but may not yet have significant revenue. Seed funding has become increasingly institutionalized with dedicated seed funds and higher valuations."),

        ("Pre-seed", "The earliest stage of institutional funding, typically smaller rounds ($100K-$1M) raised to get from idea to prototype or MVP. Pre-seed investors include angels, micro-VCs, accelerators, and occasionally friends and family. At this stage, companies often have just a founding team, a concept, and perhaps some initial customer research but rarely revenue. Pre-seed funding is used for initial product development, market validation, and building toward seed-stage metrics. The pre-seed category has emerged as seed rounds have grown larger and moved later stage."),

        ("Liquidation Preference", "A provision in preferred stock that determines the order and amount investors receive when a company is sold or liquidated before other shareholders. A standard 1x liquidation preference means investors get their money back before common stockholders (founders and employees) receive anything. If a company with a $10M investment and 1x liquidation preference sells for $8M, investors get $8M and common shareholders get nothing. Higher multiples (2x, 3x) or participating preferred structures can dramatically reduce founder returns. This is one of the most important economic terms in a term sheet."),

        ("Anti-dilution Provisions", "Protective clauses that adjust an investor's ownership or conversion price if the company raises money at a lower valuation in the future (a down round). Full ratchet anti-dilution (most investor-friendly) reprices the investor's shares as if they paid the lower price, significantly diluting founders. Weighted average anti-dilution (more balanced) adjusts the price based on the amount raised and how much lower the new price is. Broad-based weighted average is most common and least punitive. These provisions protect investors but can be devastating to founder and employee ownership in down rounds."),

        ("Drag Along Rights", "A provision that allows majority shareholders (typically investors with more than 50% ownership) to force minority shareholders (including founders and employees) to join in the sale of the company. This prevents minority shareholders from blocking an acquisition that the majority wants to pursue. For example, if investors holding 60% want to accept an acquisition offer, they can force the remaining 40% to sell on the same terms. Drag along rights ensure that small shareholders can't hold up transactions, though they typically include protections for minimum price thresholds or approval requirements."),

        ("Tag Along Rights", "A provision that allows minority shareholders to join a transaction if majority shareholders sell their stake, ensuring they receive the same terms and price per share. Also called \"co-sale rights,\" these protect smaller shareholders from being left behind when major investors exit. For example, if a VC owning 40% sells to a strategic buyer, founders and employees with tag along rights can sell a proportional amount of their shares at the same price. This prevents situations where majority shareholders negotiate a premium exit while leaving others stuck in an illiquid position."),

        ("Participating Preferred", "A preferred stock structure where investors receive their liquidation preference first, then also participate in the remaining proceeds with common shareholders as if they held common stock. This \"double-dip\" significantly reduces returns for founders and employees. For example, with $10M invested, 1x participating preferred, and a $50M exit: investors get $10M first, then share proportionally in the remaining $40M based on ownership percentage. Participating preferred heavily favors investors and is generally considered founder-unfriendly, becoming less common in recent years except in difficult fundraising environments or down rounds."),

        ("Board Seat", "A position on a company's board of directors, which has legal authority to govern the company and make major decisions. Investors often require board seats as part of investment terms, typically one seat for lead investors in Series A and beyond. The board usually consists of founder seats, investor seats, and independent seats. Board members have fiduciary duties to all shareholders and significant influence over strategy, hiring, financing, and exit decisions. Board composition is a critical negotiating point as it affects company control and governance dynamics."),

        ("Information Rights", "Contractual rights granted to investors to receive regular updates on company performance, typically including monthly or quarterly financial statements, annual budgets, and annual audited financials. These rights allow investors to monitor their investment and may include rights to visit company facilities, interview management, and review business operations. Information rights usually extend to investors who meet minimum investment thresholds. While providing transparency, founders should be aware these rights can be time-consuming and may require sharing sensitive information with parties who may have conflicts of interest."),

        ("Vesting", "The process by which founders and employees earn ownership of their equity over time, typically four years for startup equity. Vesting ensures that team members stay committed long-term and don't leave early with significant ownership. If someone leaves before fully vested, the company can repurchase unvested shares, usually at the original purchase price. Vesting schedules protect remaining team members and investors from giving away too much equity to people who don't contribute long-term value. It's now standard for even founders to have vesting schedules starting at company formation or first institutional funding."),

        ("Cliff", "An initial period in a vesting schedule during which no equity vests, typically one year for employees and sometimes founders. After the cliff period ends, all equity that would have vested during that period vests at once. For example, with a 4-year vesting schedule and 1-year cliff, an employee who leaves at 11 months gets zero equity, but if they stay 12 months, they vest 25% immediately. The cliff protects companies from giving meaningful equity to people who leave quickly while still rewarding those who stay beyond the initial period."),

        ("409A Valuation", "An independent appraisal of a company's common stock fair market value, required by IRS Section 409A to set the strike price for employee stock options. Companies must obtain 409A valuations at least annually and after significant events like funding rounds. The 409A value is typically significantly lower than preferred stock prices paid by investors because common stock lacks the rights and preferences of preferred stock. Accurate 409A valuations protect companies and employees from IRS penalties related to stock option pricing and deferred compensation rules."),

        ("Option Pool", "A reserve of company shares set aside for future issuance to employees, advisors, and consultants as stock options or other equity compensation. The option pool is typically created before a priced funding round and usually represents 10-20% of the post-money capitalization. Creating the option pool pre-money (before calculating new investor ownership) dilutes founders but not new investors, so the timing and size are key negotiation points. A properly sized option pool ensures the company can hire key talent without needing to seek shareholder approval for additional shares immediately."),

        ("Fully Diluted", "The ownership calculation that includes all outstanding shares plus all shares that could potentially be issued from convertible securities, stock options, warrants, and other convertible instruments. Fully diluted calculations give the most complete picture of ownership if all possible shares were issued. This is important for understanding true ownership percentages and is typically how investors calculate their ownership stake. The difference between basic shares outstanding and fully diluted can be significant, especially for companies with large option pools or multiple convertible notes or SAFEs outstanding."),

        ("BOM", "Bill of Materials\n\nA comprehensive list of all raw materials, components, sub-assemblies, parts, and quantities needed to manufacture a product. The BOM includes part numbers, descriptions, quantities, suppliers, and costs for each item. For hardware startups, the BOM is critical for calculating COGS, negotiating with suppliers, managing inventory, and qualifying alternative components. BOMs evolve through product development as designs change and must be meticulously maintained. Accurate BOMs enable manufacturers to source components, plan production, and help companies understand their cost structure and margins."),

        ("NRE", "Non-Recurring Engineering\n\nOne-time development and setup costs required to design and prepare a product for manufacturing, including engineering design, prototyping, tooling, molds, testing equipment, and certification. NRE costs can range from tens of thousands to millions of dollars depending on product complexity. These costs are paid upfront before production begins and are distinct from per-unit manufacturing costs. Understanding NRE is critical for hardware startups to budget properly and determine how much capital is needed. Some contract manufacturers may amortize NRE into per-unit costs for initial production runs."),

        ("MOQ", "Minimum Order Quantity\n\nThe smallest number of units a supplier or manufacturer will produce in a single production run. MOQs exist because of setup costs, efficiency requirements, and economies of scale. For example, a factory might have a 1,000-unit MOQ, meaning you must order at least 1,000 units even if you only need 100. High MOQs can strain cash flow and inventory management for early-stage hardware companies. Negotiating lower MOQs is often critical for startups, though it typically comes with higher per-unit costs. Understanding MOQs across your supply chain is essential for production planning and working capital requirements."),

        ("Design Partnership", "A collaborative relationship with an early customer who works closely with the startup to co-develop and refine a product based on their specific needs and feedback. Design partners provide critical input on features, usability, and requirements while often receiving early access, discounted pricing, or customization in return. These partnerships help validate product-market fit, de-risk development, and can lead to reference customers and case studies. Strong design partnerships often convert to paying customers and provide credibility with other prospects. The arrangement should be formalized with clear expectations, timelines, and deliverables for both parties."),

        ("Tooling Costs", "The expense of creating custom molds, dies, fixtures, jigs, and other specialized manufacturing equipment needed to produce a specific product. Tooling costs are a major component of NRE and can range from thousands to hundreds of thousands of dollars depending on complexity, materials, and precision requirements. For injection molded plastic parts, mold costs increase with complexity, size, and number of cavities. Tooling is typically owned by the company (not the manufacturer) and represents a significant upfront investment that must be amortized across production units. Tooling must be maintained and eventually replaced after producing a certain number of units."),

        ("DFM", "Design for Manufacturing\n\nThe practice of designing products to be easily, efficiently, and cost-effectively manufactured at scale. DFM involves considering manufacturing constraints, processes, and costs during the design phase rather than after. This includes minimizing part count, using standard components, designing for simple assembly, avoiding overly tight tolerances, and considering tooling requirements. Good DFM reduces manufacturing costs, improves quality, shortens production time, and prevents expensive redesigns after tooling is committed. Hardware startups should involve manufacturing partners early in the design process to optimize for DFM and avoid costly mistakes."),

        ("EVT", "Engineering Validation Test\n\nThe first major stage of hardware product development where initial prototypes are built to verify that the design meets core functional and performance requirements. EVT units are typically hand-built or produced in very small quantities (10-50 units) and may not use final manufacturing processes. The goal is to validate that the engineering design works as intended before investing in tooling. EVT reveals design flaws, performance issues, and areas for improvement. Successful EVT completion is necessary before moving to DVT."),

        ("DVT", "Design Validation Test\n\nThe second major stage of hardware development where prototypes are built using closer-to-final manufacturing processes to validate the design works reliably and meets all specifications. DVT units (typically 100-500) test reliability, durability, user experience, and manufacturability. This stage identifies design issues that only appear with production-like processes and extended testing. DVT is where DFM principles are validated and tooling is often initiated. Companies may conduct extensive testing including drop tests, environmental testing, and user trials. Successful DVT is required before committing to full production tooling and PVT."),

        ("PVT", "Production Validation Test\n\nThe final stage of hardware development where products are manufactured using final production tooling, processes, and materials to validate that manufacturing can produce units at the required quality, yield, and cost. PVT runs (typically 500-5,000 units) verify that the supply chain, assembly processes, quality control, and packaging all work at production scale. PVT units are functionally identical to final production units and are often used for beta testing, certification testing, and initial sales. Successful PVT completion means the product is ready for mass production. Issues discovered in PVT can be expensive to fix if tooling must be modified."),

        ("CM", "Contract Manufacturer\n\nA third-party company that manufactures products on behalf of another company based on the latter's designs and specifications. CMs provide manufacturing infrastructure, expertise, labor, and often procurement services, allowing hardware startups to avoid building their own factories. CMs range from small specialized shops to massive operations like Foxconn. Choosing the right CM involves evaluating their capabilities, quality systems, minimum order quantities, pricing, lead times, communication, and cultural fit. The relationship requires clear contracts covering IP protection, quality standards, payment terms, and responsibilities. Strong CM partnerships are critical for hardware startup success."),

        ("COGS", "Cost of Goods Sold\n\nThe direct costs attributable to producing products that are sold, including raw materials, components, direct labor, and manufacturing overhead. COGS excludes indirect expenses like sales, marketing, R&D, and administrative costs. For hardware products, COGS includes the BOM cost, assembly labor, packaging, and factory overhead. Understanding COGS is critical for pricing decisions, gross margin calculations, and profitability analysis. Hardware startups must track COGS carefully as it typically decreases with volume through economies of scale and supplier negotiations. COGS as a percentage of revenue directly impacts gross margin and unit economics."),

        ("Gross Margin", "The percentage of revenue remaining after subtracting COGS, calculated as (Revenue - COGS) / Revenue × 100. Gross margin indicates how much money is available to cover operating expenses and generate profit. For example, if a product sells for $100 and costs $40 to manufacture, gross margin is 60%. Hardware products typically have lower gross margins (30-50%) than software (70-90%) due to physical production costs. Investors scrutinize gross margins as an indicator of business model viability, pricing power, and scalability. Improving gross margins through cost reduction and pricing optimization is critical for hardware startups reaching profitability."),

        ("Lead Time", "The amount of time between placing an order and receiving the finished goods, encompassing component procurement, production, quality control, and shipping. Lead times for hardware products can range from weeks to months depending on complexity, supply chain, and manufacturing location. Long lead times require careful inventory planning and forecasting to avoid stockouts. Startups must understand lead times for components (which can be 12+ weeks for custom or specialized parts), production (typically 4-8 weeks), and shipping (2-8 weeks for ocean freight from Asia). Managing lead times effectively is critical for maintaining inventory levels and meeting customer demand."),

        ("First Article", "The initial production sample or small batch produced by a manufacturer to demonstrate they can meet specifications before full production begins. First article inspection (FAI) is a formal verification process where the first article is thoroughly tested against all requirements, dimensions, and quality standards. This catch potential manufacturing issues before committing to large production runs. First articles are typically produced after tooling is complete but before PVT or mass production. Approval of first articles is a contractual milestone that confirms the manufacturer can produce to specification and triggers authorization for larger production quantities."),

        ("Certification", "The formal process of testing and approving a product to meet regulatory requirements for sale in specific markets. Common certifications include FCC (electromagnetic interference/radiofrequency, USA), CE (safety and performance, Europe), UL (safety, USA), RoHS (hazardous substances, EU), and various country-specific requirements. Certification involves testing by accredited laboratories, documentation, and fees ranging from thousands to hundreds of thousands of dollars. Products cannot legally be sold in many markets without proper certification. Hardware startups must budget for certification costs and timelines (often 2-6 months) and design products with certification requirements in mind to avoid costly redesigns."),

        ("Supply Chain", "The entire network of suppliers, manufacturers, logistics providers, and distribution channels involved in producing and delivering a product to customers. For hardware startups, this includes component suppliers, contract manufacturers, shipping companies, warehouses, and fulfillment partners. Supply chain management involves coordinating these entities to optimize cost, quality, speed, and reliability. Strong supply chains provide redundancy (backup suppliers), visibility (tracking inventory and shipments), and flexibility (ability to scale up or down). Recent global events have highlighted supply chain vulnerabilities, making diversification and relationship management critical for hardware companies."),

        ("Working Capital", "The cash and liquid assets available to fund day-to-day operations, calculated as current assets minus current liabilities. For hardware companies, working capital is critical because significant cash is tied up in inventory (raw materials, work in progress, and finished goods) and accounts receivable before revenue is collected. Hardware startups often face a working capital gap where they must pay suppliers and manufacturers upfront but don't collect from customers until much later. Undercapitalized hardware companies can become profitable on paper but run out of cash due to insufficient working capital. Many hardware startups raise dedicated working capital facilities or inventory financing to manage this challenge."),

        ("ARR", "Annual Recurring Revenue\n\nThe annualized value of recurring revenue from subscriptions or contracts, calculated by taking monthly recurring revenue and multiplying by 12, or by summing all active subscription values over a year. ARR is the key metric for SaaS and subscription businesses to measure growth and company scale. It excludes one-time fees and variable usage charges (though some companies track a variant including these). ARR is forward-looking, showing expected revenue if current subscriptions continue, and is the primary metric investors use to value subscription businesses. Growing ARR consistently demonstrates product-market fit and business model viability."),

        ("MRR", "Monthly Recurring Revenue\n\nThe monthly value of all active recurring subscriptions and contracts, providing a real-time view of subscription business performance. MRR is calculated by summing the monthly value of all active subscriptions, normalizing annual or quarterly contracts to monthly figures. It's broken down into New MRR (from new customers), Expansion MRR (from upgrades/upsells), Contraction MRR (from downgrades), and Churned MRR (from cancellations). Tracking MRR and its components helps companies understand growth drivers, customer health, and revenue trends. MRR × 12 approximates ARR, though companies typically track both metrics for different purposes."),

        ("Unit Economics", "The revenue and costs associated with a single unit of the business - typically one customer for a service business or one product for a hardware business. Understanding unit economics means knowing exactly how much it costs to acquire a customer (CAC), how much revenue they generate over their lifetime (LTV), and the ratio between these (LTV:CAC ratio). Positive unit economics (LTV > CAC) indicate a sustainable business model that can scale profitably. Companies with strong unit economics can invest in growth knowing each customer adds value. Poor unit economics indicate fundamental business model problems that can't be solved by scaling alone."),

        ("CAC", "Customer Acquisition Cost\n\nThe total sales and marketing cost required to acquire a new customer, calculated by dividing total sales and marketing expenses by the number of new customers acquired in a period. CAC includes advertising spend, sales team salaries and commissions, marketing tools, events, and content creation. For example, if you spend $100,000 on sales and marketing in a quarter and acquire 50 customers, CAC is $2,000. Investors closely examine CAC relative to LTV - a healthy ratio is LTV:CAC of 3:1 or higher. Rising CAC can indicate market saturation or inefficient go-to-market strategies, while decreasing CAC suggests improving efficiency and product-market fit."),

        ("LTV", "Lifetime Value\n\nThe total revenue a company expects to generate from a customer over their entire relationship with the company. For subscription businesses, LTV is calculated as average revenue per customer per month × average customer lifetime in months × gross margin. For example, if customers pay $100/month, stay for 36 months on average, and gross margin is 80%, LTV is $2,880. LTV must significantly exceed CAC (typically 3x or higher) for a sustainable business model. Improving LTV involves increasing prices, reducing churn, and expanding accounts through upsells. LTV is a critical metric for evaluating business model viability and determining how much can be spent on customer acquisition."),

        ("Churn", "The rate at which customers cancel or stop using a product, typically expressed as a monthly or annual percentage. Customer churn counts lost customers while revenue churn (often called MRR churn or dollar churn) measures lost revenue, which can differ due to account size variations. For example, 5% monthly customer churn means losing 5% of customers each month. Churn is one of the most critical SaaS metrics - high churn makes growth extremely difficult as you're constantly replacing lost customers. Negative net revenue churn (expansion from existing customers exceeds losses from churned customers) is the gold standard. Even small improvements in churn dramatically impact long-term growth and company value."),

        ("TAM", "Total Addressable Market\n\nThe total revenue opportunity available if a product or service achieved 100% market share in its broadest definition of the market. TAM represents the maximum potential market size without any constraints. It's typically calculated top-down using industry research and market size data. For example, if there are 10 million potential customers who might pay $100 annually, TAM is $1 billion. TAM is useful for understanding overall market opportunity and communicating the vision to investors, though it's often theoretical. Investors care more about SAM and SOM which reflect realistic market capture."),

        ("SAM", "Serviceable Addressable Market\n\nThe portion of TAM that a company can realistically serve with its current product, business model, and distribution channels within geographic and market segment constraints. SAM is more specific than TAM and represents the true near-term opportunity. For example, if TAM is $1 billion globally but your product only serves North American small businesses, SAM might be $100 million. SAM is calculated by applying filters like geography, company size, industry vertical, and product fit to the broader TAM. Investors use SAM to evaluate realistic growth potential rather than theoretical maximums."),

        ("SOM", "Serviceable Obtainable Market\n\nThe portion of SAM that a company can realistically capture in the near to medium term (typically 3-5 years) given competition, go-to-market strategy, and resources. SOM represents the realistic target market share. For example, if SAM is $100 million and you expect to capture 10% over 5 years, SOM is $10 million. SOM is calculated bottom-up based on sales capacity, marketing reach, competitive positioning, and growth projections. This is the most important market metric for investors evaluating a specific company's opportunity, as it grounds market sizing in realistic business planning rather than top-down market statistics."),

        ("Revenue Model", "The strategy and mechanism by which a company generates income from its products or services. Common revenue models include: subscription (recurring fees for ongoing access), transactional (per-purchase fees), freemium (free basic tier with paid premium features), marketplace (taking a percentage of transactions), licensing (selling rights to use IP), advertising (monetizing user attention), and hardware sales (one-time product purchases). The revenue model fundamentally shapes unit economics, scalability, valuation multiples, and business operations. Choosing the right revenue model for your market and customer behavior is a critical strategic decision that's difficult to change later."),

        ("Margins", "The percentage of revenue that represents profit at various levels of the business. Gross margin is revenue minus COGS as a percentage of revenue, showing profitability on core product sales. Operating margin includes all operating expenses (sales, marketing, R&D, G&A) showing operational profitability. Net margin includes all expenses including interest and taxes, showing bottom-line profitability. Higher margins indicate pricing power, operational efficiency, and more money available for reinvestment or profit. Software companies typically have gross margins of 70-90% while hardware companies average 30-50%. Investors closely examine margins to assess business model quality and path to profitability."),

        ("P&L", "Profit and Loss statement (also called Income Statement)\n\nA financial statement showing a company's revenues, costs, and expenses over a specific period, ultimately showing whether the company made a profit or loss. The P&L follows the structure: Revenue - COGS = Gross Profit - Operating Expenses (sales, marketing, R&D, G&A) = Operating Income - Interest and Taxes = Net Income. P&L statements are typically prepared monthly, quarterly, and annually. They're critical for understanding business performance, identifying cost problems, tracking unit economics scaling, and demonstrating financial progress to investors and boards. The P&L is one of three core financial statements along with the balance sheet and cash flow statement."),

        ("Cash Flow", "The movement of money into and out of a business over a specific period, showing actual cash generation or consumption as distinct from accounting profit. Cash flow is divided into operating activities (core business operations), investing activities (capital expenditures and investments), and financing activities (raising capital, debt, dividends). A company can be profitable on paper but have negative cash flow due to timing differences in receiving revenue and paying expenses. Hardware companies often face cash flow challenges from inventory investment. The cash flow statement shows whether a company generates enough cash to sustain operations or needs external funding. Cash is oxygen for startups - running out means business death."),

        ("Break-even", "The point at which total revenue equals total costs, resulting in neither profit nor loss. Break-even analysis calculates how much revenue or how many units must be sold to cover all fixed and variable costs. For a startup, reaching break-even means the company becomes self-sustaining and no longer burns cash requiring additional fundraising. Break-even can be calculated for the overall business, for specific products, or for unit economics. Understanding the path to break-even and key drivers to get there is critical for financial planning and communicating with investors. Many growth companies intentionally operate below break-even while scaling, prioritizing growth over profitability."),

        ("GMV", "Gross Merchandise Value\n\nThe total dollar value of all transactions processed through a marketplace or platform over a period, regardless of the company's revenue from those transactions. For example, if an e-commerce marketplace processes $10 million in customer purchases but takes a 15% commission, GMV is $10 million while revenue is $1.5 million. GMV measures overall platform volume and activity but isn't the same as revenue. It's commonly used by marketplaces, e-commerce platforms, and payment processors to show scale and growth. Investors examine GMV alongside take rate (percentage of GMV captured as revenue) to understand both volume and monetization effectiveness."),

        ("ASP", "Average Selling Price\n\nThe mean price at which a product or service is sold, calculated by dividing total revenue by number of units sold. ASP helps track pricing trends over time and across customer segments. For example, if you sell 100 units generating $50,000 revenue, ASP is $500. Changes in ASP can indicate shifts in product mix (selling more premium or budget products), pricing changes, discounting patterns, or customer segment changes. Hardware companies track ASP carefully as it directly impacts revenue and margins. Increasing ASP through product improvements or market positioning is often easier than increasing volume, making it a key growth lever."),

        ("EBITDA", "Earnings Before Interest, Taxes, Depreciation, and Amortization\n\nA measure of company profitability that excludes financing decisions (interest), tax environments (taxes), and non-cash accounting charges (depreciation and amortization). EBITDA is calculated as Net Income + Interest + Taxes + Depreciation + Amortization, or alternatively as Revenue - Operating Expenses (excluding D&A). EBITDA is used to evaluate operational performance and compare companies with different capital structures and tax situations. It's commonly used in acquisition valuations and by later-stage companies. However, EBITDA can be misleading for early-stage companies and capital-intensive businesses, as it ignores capital expenditure requirements and working capital needs."),

        ("IP", "Intellectual Property\n\nIntangible assets created by human intellect that have commercial value and are legally protected. IP includes patents (protecting inventions), trademarks (protecting brands and logos), copyrights (protecting creative works), and trade secrets (protecting confidential business information). For startups, IP can be a crucial competitive advantage, asset for fundraising, and defense against competitors. Proper IP strategy involves filing patents for novel innovations, trademarking brand elements, ensuring employee IP assignment agreements, and protecting trade secrets through NDAs and internal controls. IP ownership disputes can destroy startups, so it's critical to establish clear ownership from company formation and ensure all contractors and employees assign IP to the company."),

        ("NDA", "Non-Disclosure Agreement (also called Confidentiality Agreement)\n\nA legal contract where parties agree not to disclose confidential information shared between them. NDAs are either unilateral (one party discloses to another) or mutual (both parties share confidential information). They define what information is confidential, how it can be used, how long the obligation lasts (typically 2-5 years), and remedies for breach. Startups use NDAs when sharing sensitive information with potential partners, customers, investors, or contractors. However, most VCs won't sign NDAs before initial meetings since they see many similar companies. NDAs are more common in corporate partnerships and later-stage discussions involving proprietary data."),

        ("LOI", "Letter of Intent (also called Term Sheet in some contexts)\n\nA non-binding document outlining the preliminary agreement between parties before a formal contract is executed, commonly used in acquisitions, partnerships, or major customer deals. An LOI expresses serious interest and outlines key terms like price, timeline, conditions, and responsibilities, allowing parties to align on major points before investing in expensive legal documentation. While mostly non-binding, LOIs often include binding provisions on exclusivity (preventing the seller from talking to other buyers during a negotiation period) and confidentiality. LOIs help filter serious buyers from tire-kickers and provide a framework for due diligence and definitive agreement negotiation."),

        ("MOU", "Memorandum of Understanding (also called Memorandum of Agreement)\n\nA document describing a mutual agreement between parties outlining intended actions, responsibilities, and general terms of a relationship, but typically less formal than a binding contract. MOUs are common in partnerships, joint ventures, and early-stage customer or supplier relationships. They show commitment and align parties on objectives and approach while leaving detailed terms for later formal contracts. MOUs may be entirely non-binding, partially binding, or binding depending on language and intent. They're useful for moving forward with collaborative work while legal teams finalize definitive agreements. However, ambiguity about binding vs. non-binding provisions can create disputes, so clarity is essential."),

        ("Fiduciary Duty", "The legal and ethical obligation to act in the best interest of another party, with loyalty and care. For startup founders and board members, fiduciary duty requires making decisions that benefit the company and all shareholders, not just themselves. This includes duties of care (making informed, rational decisions), loyalty (avoiding conflicts of interest and self-dealing), and good faith (acting honestly and transparently). Fiduciary duties can create tension when different shareholder classes have conflicting interests, such as in acquisition scenarios where outcomes differ based on liquidation preferences. Violating fiduciary duty can result in personal liability and removal from board positions."),

        ("MAC", "Material Adverse Change (also called Material Adverse Effect)\n\nA significant negative event or change in a company's business, financial condition, operations, or prospects that substantially impacts its value or viability. MAC clauses are common in acquisition agreements, allowing buyers to walk away if a material adverse change occurs between signing and closing. What constitutes \"material\" is often contentious and has led to high-profile legal disputes. Changes generally must be significant and specific to the company (not general market conditions) to qualify. For example, losing a customer representing 50% of revenue might be a MAC, while general economic downturns typically aren't. MAC definitions are heavily negotiated in acquisition agreements."),

        ("Representations and Warranties", "Statements of fact and promises made by one party to another in a legal agreement, typically in investment or acquisition contracts. Representations are statements about current or past facts (e.g., \"the company owns all IP described\" or \"financial statements are accurate\"). Warranties are promises about future performance or compliance. If representations and warranties are false or breached, the harmed party typically has contractual remedies including indemnification, price adjustment, or contract termination. In acquisitions, buyers conduct due diligence to verify reps and warranties, and sellers often purchase insurance to cover unknown breaches. These provisions allocate risk between parties."),

        ("Indemnification", "A contractual obligation where one party agrees to compensate another for losses, damages, or liabilities arising from specific circumstances. In startup financing, companies typically indemnify investors and board members against lawsuits or losses resulting from company operations, except for the indemnified party's own misconduct. In acquisitions, sellers indemnify buyers for breaches of representations and warranties, unknown liabilities, or specific identified risks. Indemnification provisions specify what's covered, caps on liability, survival periods (how long claims can be made), and claim procedures. These provisions allocate risk and provide recourse if contractual promises are broken."),

        ("Product-Market Fit", "The degree to which a product satisfies strong market demand, evidenced by customers actively seeking, using, paying for, and recommending the product. Achieving product-market fit means you've built something people want and are willing to pay for at a price that supports viable unit economics. Signs include organic growth, high retention, NPS above 50, customers getting upset if they couldn't use the product, and strong word-of-mouth. Marc Andreessen described it as \"being in a good market with a product that can satisfy that market.\" Most startups fail because they never achieve product-market fit. It's the critical milestone before scaling sales and marketing investment."),

        ("GTM", "Go-to-Market strategy\n\nThe plan for how a company will reach customers and achieve competitive advantage when launching products or entering markets. GTM strategy encompasses target customer segments, value proposition, pricing, sales channels (direct sales, inside sales, self-serve, partners), marketing tactics, customer success approach, and competitive positioning. For example, a PLG (product-led growth) GTM uses free trials and self-serve onboarding, while an enterprise GTM uses direct sales teams and multi-month sales cycles. GTM strategy must align with product, customer economics, and business model. Strong GTM execution is often more important than product quality for startup success."),

        ("Beachhead Market", "The first specific market segment a startup targets with intense focus to gain initial traction before expanding to adjacent markets. The beachhead strategy involves dominating a small, well-defined segment where you can achieve market leadership, establish proof points, and build momentum. For example, Facebook started with Harvard students before expanding to other colleges. A good beachhead is large enough to matter but small enough to dominate with limited resources, has customers with urgent needs, offers access to adjacent segments, and faces limited competition. Trying to serve too broad a market too early dilutes resources and prevents achieving market leadership anywhere."),

        ("Moat", "A sustainable competitive advantage that protects a company from competitors and allows it to maintain market share and pricing power over time. Common moats include: network effects (product gets better with more users, like social media), economies of scale (lower costs at higher volume), brand strength (customer loyalty and premium pricing), switching costs (expensive or difficult to leave), and proprietary technology or data. Strong moats allow companies to generate superior returns long-term and defend against competition. Investors prioritize companies with clear moats as they're more likely to build enduring valuable businesses. Identifying and strengthening moats should be an ongoing strategic priority."),

        ("Pivot", "A fundamental change in business strategy while leveraging existing assets, learning, and capabilities - typically changing target customer, problem being solved, or business model while keeping some elements constant. Famous pivots include Twitter (from Odeo's podcasting to microblogging), Instagram (from Burbn to photo-sharing), and Slack (from gaming to workplace communication). Pivots are different from failures or new startups because they build on what's working while abandoning what isn't. Successful pivots require recognizing when the current strategy isn't working, being willing to abandon sunk costs, and moving quickly to test the new direction. Many successful companies pivoted at least once."),

        ("Traction", "Objective evidence that a startup's product is gaining market acceptance, typically measured through quantitative metrics like user growth, revenue, customer acquisition, retention, engagement, or partnerships. Traction demonstrates product-market fit, validates assumptions, reduces investment risk, and proves execution capability. Examples include: 20% month-over-month user growth, $100K MRR with low churn, design partnerships with Fortune 500 companies, or 10,000 waitlist signups. Investors invest in traction more than ideas because it proves market validation. The specific metrics that constitute meaningful traction vary by business model and stage, but all traction should show clear upward momentum in key business drivers."),

        ("North Star Metric", "The single key metric that best captures the core value a company delivers to customers and predicts long-term success. The North Star Metric aligns the entire company around what matters most and guides prioritization and decision-making. Examples include: Airbnb (nights booked), Facebook (daily active users), Spotify (time spent listening), and Slack (messages sent by teams). A good North Star Metric measures customer value delivery (not vanity metrics), predicts revenue/retention, is measurable and understandable, and can be influenced by the team's work. While companies track many metrics, the North Star focuses efforts on what drives sustainable growth and customer value."),

        ("MVP", "Minimum Viable Product\n\nThe simplest version of a product that delivers core value to early customers and enables validated learning about the business model and customer needs. The MVP includes only essential features needed to solve the core problem and test key assumptions, deliberately omitting nice-to-have features. The goal is to learn maximum information with minimum effort and expense. An MVP might be a landing page, prototype, concierge service (manually delivering the value before automating), or simplified product. The MVP philosophy prevents over-building based on assumptions and enables rapid iteration based on real customer feedback. What constitutes \"viable\" depends on customer expectations and market context."),
    ]

    return terms

def generate_deck():
    """Main function to generate the Anki deck."""
    print("Generating Founder Terms Anki deck...")

    # Create model and deck
    model = create_model()
    deck = create_deck()

    # Get terms and create notes
    terms = get_terms()

    for front, back in terms:
        note = genanki.Note(
            model=model,
            fields=[front, back]
        )
        deck.add_note(note)

    # Write deck to file
    output_path = 'founder_terms.apkg'
    deck.write_to_file(output_path)

    # Verify and report
    assert os.path.exists(output_path), "Deck file not created!"
    size_mb = os.path.getsize(output_path) / (1024 * 1024)

    print(f"✓ Created deck with {len(terms)} cards")
    print(f"✓ Deck saved as: {output_path}")
    print(f"✓ File size: {size_mb:.2f} MB")

if __name__ == '__main__':
    generate_deck()
